FROM golang:latest

ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH
RUN mkdir -p "$GOPATH/src/LRaft" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH/src/LRaft

COPY . .

RUN go build -o /usr/local/bin/client LRaft/kv_client

CMD client